version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - 3001:3001
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    command: bash -c "nginx -g 'daemon off;'"
    depends_on:
      - app
    ports:
      - 80:80